config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :items do
    resources :exchanges, only: [:create]
  end
  resources :exchanges, only: [:index, :update, :destroy] do
    member do
      post 'approve'
    end
    member do
      post 'complete'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/exchange.rb
class Exchange < ApplicationRecord
  belongs_to :user
  belongs_to :item
  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?
  validates :location, length: { minimum: 5 }, presence: true
  validates :time_slot, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  include PgSearch::Model
  pg_search_scope :search_by_title_and_description,
    against: [ :title, :description ],
    using: {
      tsearch: { prefix: true }
    }

  belongs_to :user
  has_many_attached :photos

  validates :title, length: { minimum: 5 }, presence: true
  validates :description, presence: true
  validates :condition, inclusion: { in: %w[Excellent Good Average Bad Broken] }, presence: true
  validates :number_available, numericality: { greater_than_or_equal_to: 1 }, presence: true
  validates :year_made, numericality: { greater_than_or_equal_to: 1990 }
  validates :photos, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :exchanges
  has_many :items
  has_one_attached :photo

  validates :name, length: { minimum: 3, maximum: 50 }, uniqueness: true, presence: true
  validates :phone_number, length: { minimum: 8, maximum: 14 }, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :phone_number, :photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :phone_number, :photo])
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/exchanges_controller.rb
class ExchangesController < ApplicationController
  before_action :set_item, only: [:create]

  def index
    @exchange = policy_scope(Exchange.where.not(completed: true))
    @items = policy_scope(Item)
    @user_exchanges = @exchange.select do |exchange|
      exchange.user_id == current_user.id
    end
    @user_items = return_filtered_items(@items)
    @markers = return_markers
    authorize @exchange
  end

  def create
    @exchange = Exchange.new(exchanges_params)
    @exchange.item = @item
    @exchange.user = current_user
    @exchange.requested = true
    authorize @exchange

    if @exchange.save
      redirect_to item_path(@item)
    end
  end

  def approve
    @exchange = Exchange.find(params[:id])
    @exchange.approved = true
    @exchange.save
    authorize @exchange
    redirect_to exchanges_path, flash: { success: "Message" }
  end

  def complete
    @exchange = Exchange.find(params[:id])
    @exchange.completed = true
    @exchange.save
    authorize @exchange
    redirect_to exchanges_path, flash: { success: "Message" }
  end

  def destroy
    @exchange = Exchange.find(params[:id])
    @exchange.destroy
    authorize @exchange
    redirect_to exchanges_path, flash: { success: "Message" }
  end

  private

  def exchanges_params
    params.require(:exchange).permit(:location, :method, :time_slot, :approved)
  end

  def set_item
    @item = Item.find(params[:item_id])
  end

  def return_markers
    Exchange.joins(:item).where("(items.user_id = #{current_user.id}
      OR exchanges.user_id = #{current_user.id}) AND exchanges.requested = true
      AND exchanges.completed = false").geocoded.map do |exchange|
      {
        lat: exchange.latitude,
        lng: exchange.longitude,
        info_window: render_to_string(partial: "info_window", locals: { exchange: exchange })
      }
    end
  end

  def return_filtered_items(items)
    @exchange_completed = policy_scope(Exchange.where(completed: true))
    @exchange_completed_id = @exchange_completed.map do |exchange|
      exchange.item_id
    end
    @user_items = items.select do |item|
      item.user_id == current_user.id
    end
    @user_items = @user_items.reject do |item|
      @exchange_completed_id.include?(item.id)
    end
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: %i[show edit update destroy]

  # GET / items
  def index
    @items = policy_scope(Item)
  end

  # GET /items/:id
  def show
    @exchanges = Exchange.all
    @exchange = @exchanges.find_by(item_id: @item.id)
  end

  # GET /items/new
  def new
    @item = Item.new
    authorize @item
  end

  # POST /items
  def create
    @item = Item.new(item_params)
    @item.user = current_user
    authorize @item

    if @item.save
      redirect_to @item
    else
      render :new
    end
  end

  # GET /items/:id/edit
  def edit
  end

  # PATCH /items/:id
  def update
    if @item.update(item_params)
      redirect_to @item
    else
      render :edit
    end
  end

  # DELETE /items/:id
  def destroy
    @item.destroy
    redirect_to items_path
  end

  private

  def set_item
    @item = Item.find(params[:id])
    authorize @item
  end

  def item_params
    params.require(:item).permit(:title, :description, :condition, :year_made, :number_available, photos: [])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
    if params[:query].present?
      @items = Item.search_by_title_and_description(params[:query])
    else
      @items = Item.all
    end

    @exchanges = Exchange.all.map(&:item_id)

    @items_filtered = @items.reject do |item|
      @exchanges.include?(item.id)
    end


    if current_user.present?
      session[:count] = Exchange.joins(:item).where("(items.user_id = #{current_user.id}
    OR exchanges.user_id = #{current_user.id}) AND exchanges.requested = true
    AND exchanges.approved = false").count
    else
      @count = ""
    end 
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/exchanges/_info_window.html.erb
<h2><%= @items.find(exchange.item_id).title %></h2>
<p><%= exchange.method %></p>
<p><%= exchange.location %></p>
</p><%= exchange.time_slot.split('T').first %>, <%= exchange.time_slot.split('T').last %><p>
<% if exchange.user_id == @current_user.id %>
  <p>Owner: <%= User.find(Item.find(exchange.item_id).user_id).name %> </p>
  <% if exchange.approved %>
  <p>Transaction Approved</p>
  <% else %>
  <p>Waiting for owner to respond!</p>
  <% end %>
<% else %>
  <p>Requestor: <%= User.find(exchange.user_id).name %></p>
  <% if exchange.approved %>
  <p>Transaction Approved</p>
  <% else %>
  <p>Someone wants to trade with you!</p>
  <% end %>
<% end %>

app/views/exchanges/index.html.erb
<div class="container align-justify-center">
  <br>
  <h1 class="px-0">Exchanges</h1>
  <h2 class="px-3" id="header-request">My requests</h2>
  <br>
  <ul>
    <% @user_exchanges.each do |exchange| %>
      <li><%= link_to @items.find(exchange.item_id).title, item_path(exchange.item_id) %>
      <% if exchange.completed %>
        <i class="fas fa-recycle"></i> Exchange is completed!
      <% elsif exchange.approved %>
      <i class="far fa-check-circle"></i>
        <% if exchange.method == "Delivery" %>
          <%= exchange.method %> from
        <% else %>
          <%= exchange.method %> with
        <% end %>
      <%= User.find(@items.find(exchange.item_id).user_id).name %> confirmed at <%= exchange.location %> on <%= exchange.time_slot.split('T').first %>, <%= exchange.time_slot.split('T').last %>
      <% else %>
        <i class="far fa-paper-plane"></i>
      <% end %>
      </li>
    <% end %>
  </ul>
  <br>
  <h2 class="px-3" id="header-request">My items</h2>
  <br>
  <ul>
    <% @user_items.each do |item| %>
      <li><%= link_to item.title, item_path(item) %>
      <% if @exchange.find_by(item_id: item.id)%>
        <% if @exchange.find_by(item_id: item.id).completed %>
          <i class="fas fa-recycle"></i> Item successfully recycled!
        <% elsif @exchange.find_by(item_id: item.id).approved %>
          <i class="far fa-check-circle"></i>
          <% if @exchange.find_by(item_id: item.id).method == "Delivery" %>
            <%= @exchange.find_by(item_id: item.id).method %> for
          <% else %>
            <%= @exchange.find_by(item_id: item.id).method %> with
          <% end %>
          <%= User.find(@exchange.find_by(item_id: item.id).user_id).name %> confirmed at <%= @exchange.find_by(item_id: item.id).location %> on <%= @exchange.find_by(item_id: item.id).time_slot.split('T').first %>, <%= @exchange.find_by(item_id: item.id).time_slot.split('T').last %>
          <%= button_to "Transaction Completed", complete_exchange_path(@exchange.find_by(item_id: item.id)), method: :post, class: "btn btn-primary", form: {style: 'display:inline-block;'} %>
        <% else %>
          <i class="far fa-envelope"></i> <%= User.find(@exchange.find_by(item_id: item.id).user_id).name %> sent an exchange request.
          <%= button_to "Agree to Trade", approve_exchange_path(@exchange.find_by(item_id: item.id)), method: :post, class: "btn btn-primary", form: {style: 'display:inline-block;'} %>
          <%= link_to "Decline", exchange_path(@exchange.find_by(item_id: item.id)), method: :delete, class: "btn btn-danger", form: {style: 'display:inline-block;'}, data: { confirm: "Are you sure?" }%>
        <% end %>
      <% else  %>
        <i class="far fa-paper-plane"></i>
      <% end %>
      </li>
    <% end %>
  </ul>
  <br>
  <h2 class="px-3" id="header-request">Location of Exchanges</h2>
  <br>

  <div class="container shadow p-3 mb-5" id="map"
      style="width: 95%; height: 700px;"
      data-markers="<%= @markers.to_json %>"
      data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>
  </div>
  <br>

</div>

app/views/items/edit.html.erb
<div class="container align-justify-center">
  <br>
  <% content_for(:title, "Edit Item") %>
  <h1>Edit Item</h1>
  <%= simple_form_for @item, url: item_path do |f| %>
    <%= f.error_notification %>

    <%= f.input :title, placeholder: 'Macbook', label:'Give a sexy Title:' %>

    <%= f.input :description, placeholder: 'Great for student', label:'Description:' %>

    <%= f.input :condition, placeholder: 'Excellent', :collection => %w[Excellent Good Average Bad Broken] %>

    <%= f.input :year_made, placeholder: '2020', label:'Year Made:', min_max: true %>

    <%= f.input :number_available, placeholder: '1', label:'Number Available:', min_max: true %>

    <%= f.input :photos, as: :file, input_html: { multiple: true }, label:'Upload Photos' %>

    <%= f.button :submit, class: "btn-primary" %>
    <%= link_to 'Cancel', @item, class: "btn btn-outline-primary" %>
  <% end %>
</div>

app/views/items/new.html.erb
<div class="container align-justify-center">
  <br>
  <% content_for(:title, "New Item") %>
  <h1>New Item</h1>
  <%= simple_form_for @item, url: items_path do |f| %>
    <%= f.error_notification %>

    <%= f.input :title, placeholder: 'Macbook', label:'Give a sexy Title:' %>

    <%= f.input :description, placeholder: 'Great for student', label:'Description:' %>

    <%= f.input :condition, placeholder: 'Excellent', :collection => %w[Excellent Good Average Bad Broken] %>

    <%= f.input :year_made, placeholder: '2020', label:'Year Made:', min_max: true %>

    <%= f.input :number_available, placeholder: '1', label:'Number Available:', min_max: true %>

    <%= f.input :photos, as: :file, input_html: { multiple: true }, class:'btn-primary', label:'Upload Photos' %>

    <%= f.button :submit, class: "btn btn-primary" %>
    <%= link_to 'Cancel', root_path, class: "btn btn-outline-primary" %>
  <% end %>
</div>

app/views/items/show.html.erb
<div class="container align-justify-center">
  <br>
  <div id="carouselExampleIndicators" class="carousel slide mt-4 shadow p-3 mb-5 bg-white rounded" data-ride="carousel">
    <ol class="carousel-indicators">
      <% if @item.photos.length > 1 %>
        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
      <% else %>
        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
      <% end %>
    </ol>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <%= cl_image_tag @item.photos[0].key, crop: :fill, class: "d-block w-100", alt: "user uploaded image" %>
      </div>
      <% @item.photos[1..-1].each do |photo| %>
        <div class="carousel-item">
          <%= cl_image_tag photo.key, crop: :fill, class: "d-block w-100", alt: "user uploaded image" %>
        </div>
      <% end %>
    </div>

    <% if @item.photos.length > 1 %>
      <button class="carousel-control-prev" type="button" data-target="#carouselExampleIndicators" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </button>
      <button class="carousel-control-next" type="button" data-target="#carouselExampleIndicators" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </button>
    <% end %>
  </div>
  <br>

  <div class="row">
    <div class="col-8">
      <div class="card item-show-card mb-3 mt-4">
        <div class="card-body m-2">
          <div class="card-title">
            <h3><%= @item.title %></h3>
          </div>
          <div class="card-subtitle text-muted">
            <% ary = @item.created_at.to_s.split(' ') %>
            <h6>Posted on <%= ary.first %></h6>
          </div>
          <div class="card-text mt-3 mb-2 border-bottom d-flex justify-content-start">
            <h5 class="mr-4 mb-3"><i class="far fa-check-square"></i> <%= @item.condition %></h5>
            <h5 class="mr-4 mb-3"><i class="far fa-calendar-alt"></i> <%= @item.year_made %></h5>
            <h5 class="mb-3"><i class="fas fa-shopping-cart"></i> <%= @item.number_available %></h5>
          </div>
          <div class="card-text mt-3">
            <h2>Description</h2>
            <p><%= @item.description %></p>
          </div>
        </div>
      </div>
    </div>

    <div class="col-4">
      <div class="card item-show-card mb-3 mt-4">
        <div class="card-body m-2">
          <div class="card-title d-flex justify-content-start align-items-center border-bottom mb-3">
            <% if @item.user.photo.attached? %>
              <%= cl_image_tag @item.user.photo.key, height: 40, width: 40, crop: :fill, class: "avatar mb-3" %>
            <% else %>
              <%= image_tag "http://placekitten.com/g/200/200", class: "avatar mb-3" %>
            <% end %>
              <h5 class="ml-2 mb-3"><%= @item.user.name %></h5>
          </div>
          <% if policy(@item).update? && policy(@item).destroy? %>
            <% if @exchange.nil? %>
              <%= link_to 'View exchange requests', exchanges_path, class: "btn btn-primary mb-4", style: "width: 100%" %>
              <div><i class="far fa-edit mr-2"></i><%= link_to 'Edit Listing', edit_item_path(@item), class: "text-decoration-none" %></div>
              <div class="delete mt-2"><i class="far fa-trash-alt mr-2 text-danger"></i><%= link_to 'Delete', @item, method: :delete, data: { confirm: 'Are you sure?' }, class: "text-danger text-decoration-none" %></div>
            <% elsif @exchange.completed %>
              <div>Item successfully recycled!</div>
              <div class="delete mt-2"><i class="far fa-trash-alt mr-2 text-danger"></i><%= link_to 'Delete', @item, method: :delete, data: { confirm: 'Are you sure?' }, class: "text-danger text-decoration-none" %></div>
            <% elsif @exchange.approved %>
              <%= link_to 'You accepted the request!', exchanges_path, class: "btn btn-primary mb-4", style: "width: 100%" %>
            <% else %>
              <%= link_to 'You have an exchange request!', exchanges_path, class: "btn btn-primary mb-4", style: "width: 100%" %>
              <div><i class="far fa-edit mr-2"></i><%= link_to 'Edit Listing', edit_item_path(@item), class: "text-decoration-none" %></div>
            <% end %>
          <% elsif @exchange.nil? %>
            <div class="exchange-form mt-4">
              <h3>Exchange request</h3>
                <div class="mt-3">
                  <%= simple_form_for [ @item, Exchange.new ] do |f| %>
                    <%= f.input :method, collection: ['Delivery', 'Meet-up'] %>
                    <%= f.input :location, label: 'Meet-up Location/Delivery Address' %>
                    <%= f.input :time_slot, label: 'Meet-up Date & Time', as: :datetime, html5: true %>
                    <%= f.submit 'Send exchange request', class: "btn btn-primary", style: "width: 100%" %>
                  <% end %>
                </div>
            </div>
          <% elsif @exchange.user_id == current_user.id && @exchange.completed %>
            <div>Exchange is completed!</div>
          <% elsif @exchange.user_id == current_user.id && @exchange.approved %>
            <div>Your request is accepted!</div>
          <% elsif @exchange.user_id == current_user.id %>
            <div>Your request is pending...</div>
          <% else %>
            <div>Sorry... Item is no longer available!</div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecycleMe</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <%= stylesheet_pack_tag 'application' %>
  </head>

  <body>
    <%= render 'components/navbar' %>
    <%= render 'components/flashes' %>
    <%= yield %>
    <%= render 'components/footer' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container-fluid align-justify-center">
  <a href="" class="top-link hide" id="scrollToTop"><i class="fas fa-3x fa-chevron-circle-up"></i></a>

  <div class="text-center py-3">
    <h1 class="py-1 my-3">3 Easy Steps<br>
    To Pass On Your <i class="far fa-heart"></i>ed Electronics</h1>
  </div>

  <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
    <div class="carousel-inner">
      <div class="carousel-item active">
        <%= image_tag "https://images.unsplash.com/photo-1497250681960-ef046c08a56e?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto", class: "w-100", alt: "First slide" %>
          <div class="carousel-caption">
            <h1><i class="fas fa-th-list"></i><br>
            List Item</h1>
            <p>Share More Info on Your Item</p>
          </div>
      </div>
      <div class="carousel-item">
        <%= image_tag "https://images.unsplash.com/photo-1497250681960-ef046c08a56e?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto", class: "w-100", alt: "Second slide" %>
          <div class="carousel-caption">
            <h1> <i class="far fa-calendar-check"></i> <br>
            Schedule A Meetup</h1>
            <p>Accept Request for & Schedule Exchange</p>
          </div>
      </div>
      <div class="carousel-item">
        <%= image_tag "https://images.unsplash.com/photo-1497250681960-ef046c08a56e?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto", class: "w-100", alt: "Third slide" %>
          <div class="carousel-caption d-none d-md-block">
            <h1><i class="far fa-hand-spock"></i><br>
            Pass It On</h1>
            <p>Your Item With New Owners</p>
          </div>
      </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div>

<div class="container-fluid">
  <br>
  <h2 class="py-3 text-center">All Our Pre-loved Items (<%= @items_filtered.length %>)</h2>
      <br>
        <div class="row">
          <% @items_filtered.reverse_each do |item| %>
            <div class="col-sm-4 d-flex">
              <div class="card flex-fill py-0 px-0 shadow p-3 mb-5" data-aos="zoom-in-up" data-aos-duration="1000">
                <% if item.photos.attached? %>
                  <%= cl_image_tag item.photos.first.key, height: 250, crop: :fill, class: "card-img-top", alt: "user uploaded image" %>
                <% else %>
                  <%= image_tag "https://images.unsplash.com/photo-1464380573004-8ca85a08751a?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1470&q=80" %>
                <% end %>
                 <div class="card-body">
                  <h5 class="card-title"><%= item.title %></h5>
                  <p class="card-text"><%= item.description %></p>
                 </div>
                <div class="card-footer d-flex justify-content-between p-3">
                  <%= link_to 'More info', item_path(item), class: "text-light text-decoration-none" %>
                  <h6 class="text-light m-0">Posted on: <%= item.created_at.to_s.split(' ').first %></h6>
                </div>
              </div>
            </div>
          <% end %>
        </div>
  <div>
</div>